In [1]:
import pandas as pd

In [2]:
games = pd.read_csv("games.csv")

In [3]:
games.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

In [4]:
games["Team"] = games["Team"].str.replace(r"[\[\]']", "",regex=True)
games["Genres"] = games["Genres"].str.replace(r"[\[\]']", "",regex=True)
games["Reviews"] = games["Reviews"].str.replace(r"[\[\]']", "",regex=True)

In [5]:
games.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","Bandai Namco Entertainment, FromSoftware",4.5,3.9K,3.9K,"Adventure, RPG","Elden Ring is a fantasy, action and open world...","""The first playthrough of elden ring is one of...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",Supergiant Games,4.3,2.9K,2.9K,"Adventure, Brawler, Indie, RPG",A rogue-lite hack and slash dungeon crawler in...,convinced this is a roguelike for people who d...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","Nintendo, Nintendo EPD Production Group No. 3",4.4,4.3K,4.3K,"Adventure, RPG",The Legend of Zelda: Breath of the Wild is the...,This game is the game (that is not CS:GO) that...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","tobyfox, 8-4",4.2,3.5K,3.5K,"Adventure, Indie, RPG, Turn Based Strategy","A small child falls into the Underground, wher...",soundtrack is tied for #1 with nier automata. ...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",Team Cherry,4.4,3K,3K,"Adventure, Indie, Platform",A 2D metroidvania with an emphasis on close co...,"""this games worldbuilding is incredible, with ...",21K,2.4K,8.3K,2.3K

In [6]:
games = games.drop(columns=["Unnamed: 0"])

In [7]:
games.head()

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,"Feb 25, 2022","Bandai Namco Entertainment, FromSoftware",4.5,3.9K,3.9K,"Adventure, RPG","Elden Ring is a fantasy, action and open world...","""The first playthrough of elden ring is one of...",17K,3.8K,4.6K,4.8K
1,Hades,"Dec 10, 2019",Supergiant Games,4.3,2.9K,2.9K,"Adventure, Brawler, Indie, RPG",A rogue-lite hack and slash dungeon crawler in...,convinced this is a roguelike for people who d...,21K,3.2K,6.3K,3.6K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","Nintendo, Nintendo EPD Production Group No. 3",4.4,4.3K,4.3K,"Adventure, RPG",The Legend of Zelda: Breath of the Wild is the...,This game is the game (that is not CS:GO) that...,30K,2.5K,5K,2.6K
3,Undertale,"Sep 15, 2015","tobyfox, 8-4",4.2,3.5K,3.5K,"Adventure, Indie, RPG, Turn Based Strategy","A small child falls into the Underground, wher...",soundtrack is tied for #1 with nier automata. ...,28K,679,4.9K,1.8K
4,Hollow Knight,"Feb 24, 2017",Team Cherry,4.4,3K,3K,"Adventure, Indie, Platform",A 2D metroidvania with an emphasis on close co...,"""this games worldbuilding is incredible, with ...",21K,2.4K,8.3K,2.3K

In [8]:
games.isnull().sum()

Title                 0
Release Date          0
Team                  1
Rating               13
Times Listed          0
Number of Reviews     0
Genres                0
Summary               1
Reviews               0
Plays                 0
Playing               0
Backlogs              0
Wishlist              0
dtype: int64

In [9]:
games = games.dropna()
games.head()

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,"Feb 25, 2022","Bandai Namco Entertainment, FromSoftware",4.5,3.9K,3.9K,"Adventure, RPG","Elden Ring is a fantasy, action and open world...","""The first playthrough of elden ring is one of...",17K,3.8K,4.6K,4.8K
1,Hades,"Dec 10, 2019",Supergiant Games,4.3,2.9K,2.9K,"Adventure, Brawler, Indie, RPG",A rogue-lite hack and slash dungeon crawler in...,convinced this is a roguelike for people who d...,21K,3.2K,6.3K,3.6K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","Nintendo, Nintendo EPD Production Group No. 3",4.4,4.3K,4.3K,"Adventure, RPG",The Legend of Zelda: Breath of the Wild is the...,This game is the game (that is not CS:GO) that...,30K,2.5K,5K,2.6K
3,Undertale,"Sep 15, 2015","tobyfox, 8-4",4.2,3.5K,3.5K,"Adventure, Indie, RPG, Turn Based Strategy","A small child falls into the Underground, wher...",soundtrack is tied for #1 with nier automata. ...,28K,679,4.9K,1.8K
4,Hollow Knight,"Feb 24, 2017",Team Cherry,4.4,3K,3K,"Adventure, Indie, Platform",A 2D metroidvania with an emphasis on close co...,"""this games worldbuilding is incredible, with ...",21K,2.4K,8.3K,2.3K

In [10]:
games = games.drop_duplicates()
games.head()

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,"Feb 25, 2022","Bandai Namco Entertainment, FromSoftware",4.5,3.9K,3.9K,"Adventure, RPG","Elden Ring is a fantasy, action and open world...","""The first playthrough of elden ring is one of...",17K,3.8K,4.6K,4.8K
1,Hades,"Dec 10, 2019",Supergiant Games,4.3,2.9K,2.9K,"Adventure, Brawler, Indie, RPG",A rogue-lite hack and slash dungeon crawler in...,convinced this is a roguelike for people who d...,21K,3.2K,6.3K,3.6K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","Nintendo, Nintendo EPD Production Group No. 3",4.4,4.3K,4.3K,"Adventure, RPG",The Legend of Zelda: Breath of the Wild is the...,This game is the game (that is not CS:GO) that...,30K,2.5K,5K,2.6K
3,Undertale,"Sep 15, 2015","tobyfox, 8-4",4.2,3.5K,3.5K,"Adventure, Indie, RPG, Turn Based Strategy","A small child falls into the Underground, wher...",soundtrack is tied for #1 with nier automata. ...,28K,679,4.9K,1.8K
4,Hollow Knight,"Feb 24, 2017",Team Cherry,4.4,3K,3K,"Adventure, Indie, Platform",A 2D metroidvania with an emphasis on close co...,"""this games worldbuilding is incredible, with ...",21K,2.4K,8.3K,2.3K

In [11]:
def convert_k(x):
    x = str(x).upper().strip()
    if "K" in x:
        return float(x.replace("K", "")) * 1000
    else:
        return float(x)


games["Times Listed"] = games["Times Listed"].apply(convert_k)
games["Number of Reviews"] = games["Number of Reviews"].apply(convert_k)
games["Plays"] = games["Plays"].apply(convert_k)
games["Playing"] = games["Playing"].apply(convert_k)
games["Backlogs"] = games["Backlogs"].apply(convert_k)
games["Wishlist"] = games["Wishlist"].apply(convert_k)

In [12]:
games.head()

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,"Feb 25, 2022","Bandai Namco Entertainment, FromSoftware",4.5,3900.0,3900.0,"Adventure, RPG","Elden Ring is a fantasy, action and open world...","""The first playthrough of elden ring is one of...",17000.0,3800.0,4600.0,4800.0
1,Hades,"Dec 10, 2019",Supergiant Games,4.3,2900.0,2900.0,"Adventure, Brawler, Indie, RPG",A rogue-lite hack and slash dungeon crawler in...,convinced this is a roguelike for people who d...,21000.0,3200.0,6300.0,3600.0
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","Nintendo, Nintendo EPD Production Group No. 3",4.4,4300.0,4300.0,"Adventure, RPG",The Legend of Zelda: Breath of the Wild is the...,This game is the game (that is not CS:GO) that...,30000.0,2500.0,5000.0,2600.0
3,Undertale,"Sep 15, 2015","tobyfox, 8-4",4.2,3500.0,3500.0,"Adventure, Indie, RPG, Turn Based Strategy","A small child falls into the Underground, wher...",soundtrack is tied for #1 with nier automata. ...,28000.0,679.0,4900.0,1800.0
4,Hollow Knight,"Feb 24, 2017",Team Cherry,4.4,3000.0,3000.0,"Adventure, Indie, Platform",A 2D metroidvania with an emphasis on close co...,"""this games worldbuilding is incredible, with ...",21000.0,2400.0,8300.0,2300.0

In [13]:
vgsales = pd.read_csv("vgsales.csv")

In [14]:
vgsales.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [15]:
vgsales.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [16]:
vgsales = vgsales.dropna()
vgsales.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [17]:
vgsales = vgsales.drop_duplicates()
vgsales.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [18]:
games.rename(columns={"Title" : "Name"},inplace = True)

In [19]:
games.head()

,Name,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,"Feb 25, 2022","Bandai Namco Entertainment, FromSoftware",4.5,3900.0,3900.0,"Adventure, RPG","Elden Ring is a fantasy, action and open world...","""The first playthrough of elden ring is one of...",17000.0,3800.0,4600.0,4800.0
1,Hades,"Dec 10, 2019",Supergiant Games,4.3,2900.0,2900.0,"Adventure, Brawler, Indie, RPG",A rogue-lite hack and slash dungeon crawler in...,convinced this is a roguelike for people who d...,21000.0,3200.0,6300.0,3600.0
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","Nintendo, Nintendo EPD Production Group No. 3",4.4,4300.0,4300.0,"Adventure, RPG",The Legend of Zelda: Breath of the Wild is the...,This game is the game (that is not CS:GO) that...,30000.0,2500.0,5000.0,2600.0
3,Undertale,"Sep 15, 2015","tobyfox, 8-4",4.2,3500.0,3500.0,"Adventure, Indie, RPG, Turn Based Strategy","A small child falls into the Underground, wher...",soundtrack is tied for #1 with nier automata. ...,28000.0,679.0,4900.0,1800.0
4,Hollow Knight,"Feb 24, 2017",Team Cherry,4.4,3000.0,3000.0,"Adventure, Indie, Platform",A 2D metroidvania with an emphasis on close co...,"""this games worldbuilding is incredible, with ...",21000.0,2400.0,8300.0,2300.0

In [20]:
merged = pd.merge(games, vgsales, on = "Name",how = "inner")
merged.head()

,Name,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,73,X360,2013.0,Misc,Microsoft Game Studios,5.58,2.83,0.02,0.77,9.20
1,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,169,PS3,2014.0,Misc,Sony Computer Entertainment,1.97,2.51,0.00,0.94,5.42
2,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,298,PS4,2014.0,Misc,Sony Computer Entertainment Europe,1.38,1.87,0.12,0.65,4.02
3,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,644,XOne,2014.0,Misc,Microsoft Game Studios,1.43,0.76,0.00,0.22,2.41
4,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,715,PSV,2014.0,Misc,Sony Computer Entertainment Europe,0.28,0.79,0.87,0.32,2.25

In [21]:
merged.isnull().sum()

Name                 0
Release Date         0
Team                 0
Rating               0
Times Listed         0
Number of Reviews    0
Genres               0
Summary              0
Reviews              0
Plays                0
Playing              0
Backlogs             0
Wishlist             0
Rank                 0
Platform             0
Year                 0
Genre                0
Publisher            0
NA_Sales             0
EU_Sales             0
JP_Sales             0
Other_Sales          0
Global_Sales         0
dtype: int64

In [22]:
def convert_k(x):
    x = str(x).upper().strip()
    if "K" in x:
        return float(x.replace("K", "")) * 1000
    else:
        return float(x)
    
merged["Times Listed"] = merged["Times Listed"].apply(convert_k)
merged["Number of Reviews"] = merged["Number of Reviews"].apply(convert_k)
merged["Plays"] = merged["Plays"].apply(convert_k)
merged["Playing"] = merged["Playing"].apply(convert_k)
merged["Backlogs"] = merged["Backlogs"].apply(convert_k)
merged["Wishlist"] = merged["Wishlist"].apply(convert_k)

In [23]:
merged.head()

,Name,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,73,X360,2013.0,Misc,Microsoft Game Studios,5.58,2.83,0.02,0.77,9.20
1,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,169,PS3,2014.0,Misc,Sony Computer Entertainment,1.97,2.51,0.00,0.94,5.42
2,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,298,PS4,2014.0,Misc,Sony Computer Entertainment Europe,1.38,1.87,0.12,0.65,4.02
3,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,644,XOne,2014.0,Misc,Microsoft Game Studios,1.43,0.76,0.00,0.22,2.41
4,Minecraft,"Nov 18, 2011",Mojang Studios,4.3,2300.0,2300.0,"Adventure, Simulator",Minecraft focuses on allowing the player to ex...,Minecraft is what you make of it. Unfortunatel...,33000.0,...,715,PSV,2014.0,Misc,Sony Computer Entertainment Europe,0.28,0.79,0.87,0.32,2.25

In [24]:
import mysql.connector

In [25]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345",

)
cursor = conn.cursor()

In [26]:
cursor.execute("CREATE DATABASE IF NOT EXISTS video_data")
print("MySQL database 'video_data' created successfully!")

MySQL database 'video_data' created successfully!

In [27]:
cursor.execute("use video_data")

In [28]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS games (
    `Name` TEXT,
    `Release_Date` TEXT,
    `Team` TEXT,
    `Rating` FLOAT,
    `Times_Listed` FLOAT,
    `Number_of_Reviews` FLOAT,
    `Genres` TEXT,
    `Summary` TEXT,
    `Reviews` TEXT,
    `Plays` FLOAT,
    `Playing` FLOAT,
    `Backlogs` FLOAT,
    `Wishlist` FLOAT
)
""")

conn.commit()

In [29]:
for index, row in games.iterrows():
    cursor.execute("""
        INSERT INTO games (`Name`, `Release_Date`, `Team`, `Rating`, `Times_Listed`, 
                           `Number_of_Reviews`, `Genres`, `Summary`, `Reviews`, 
                           `Plays`, `Playing`, `Backlogs`, `Wishlist`)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, tuple(row))

In [30]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    `Rank` INT,
    `Name` TEXT,
    `Platform` TEXT,
    `Year` FLOAT,
    `Genre` TEXT,
    `Publisher` VARCHAR(255),
    `NA_Sales` FLOAT,
    `EU_Sales` FLOAT,
    `JP_Sales` FLOAT,
    `Other_Sales` FLOAT,
    `Global_Sales` FLOAT
)
""")

conn.commit()

In [31]:
for index, row in vgsales.iterrows():
    cursor.execute("""
        INSERT INTO sales (`Rank`,`Name`, `Platform`, `Year`, `Genre`, `Publisher`, 
                            `NA_Sales`, `EU_Sales`, `JP_Sales`, `Other_Sales`, `Global_Sales`)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, tuple(row))

In [32]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS merged (
    `Name` TEXT,
    `Release_Date` TEXT,
    `Team` TEXT,
    `Rating` FLOAT,
    `Times_Listed` FLOAT,
    `Number_of_Reviews` FLOAT,
    `Genres` TEXT,
    `Summary` TEXT,
    `Reviews` TEXT,
    `Plays` FLOAT,
    `Playing` FLOAT,
    `Backlogs` FLOAT,
    `Wishlist` FLOAt,
    `Rank` INT,
    `Platform` TEXT,
    `Year` FLOAT,
    `Genre` TEXT,
    `Publisher` TEXT,
    `NA_Sales` FLOAT,
    `EU_Sales` FLOAT,
    `JP_Sales` FLOAT,
    `Other_Sales` FLOAT,
    `Global_Sales` FLOAT
)
""")

conn.commit()

In [33]:
for index, row in merged.iterrows():
    cursor.execute("""
        INSERT INTO merged (`Name`, `Release_Date`, `Team`, `Rating`, `Times_Listed`, 
                            `Number_of_Reviews`, `Genres`, `Summary`, `Reviews`, 
                            `Plays`, `Playing`, `Backlogs`, `Wishlist`, 
                            `Rank`, `Platform`, `Year`, `Genre`, `Publisher`, 
                            `NA_Sales`, `EU_Sales`, `JP_Sales`, `Other_Sales`, `Global_Sales`)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, tuple(row))